[package]
name = "blog_generator"
version = "0.1.0"
authors = ["kernuac"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = "*"
serde = "*"
serde_derive = "*"
serde_yaml = "*"
serde_json = "*"
config = "*"